### ISSUE TITLE
Join the org

### ISSUE THREAD

**Issue by VasudevJaiswal** [ayushman17/ayushman17#1]
[Click Here](https://github.com/Jaidevstudio/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)

**Comment by ayushman17** [comment]
Hello @VasudevJaiswal 👋🏻,

Thank you for reaching out. 😁
At this time, I am not interested in this personally. However, if you would like I can certainly forward this to any colleagues, I think may be interested.

**Comment by VasudevJaiswal** [comment]
@ayushman17 
1. Thank you
